GET http://localhost:3000/api/animals/

###

GET http://localhost:3000/api/animals/93244cd0-01b9-11ec-9841-a909d501f613

###

POST http://localhost:3000/api/animals
Content-Type: application/json

{
    "name": "ormensssss",
    "animalType": "hund",
    "otherInfo": "Bichon frisé"
}

###
DELETE http://localhost:3000/api/animals/1cd70080-01ba-11ec-a35b-d181e9876b6d

###

PUT http://localhost:3000/api/animals/1
Content-Type: application/json

{
    "name": "MÖRA",
    "animalType": "igelkott",
    "otherInfo": "inget"
}


