GET http://localhost:3000/api/animals/

###

GET http://localhost:3000/api/animals/ccd19a10-071c-11ec-97af-f3a328a84f14

###

POST http://localhost:3000/api/animals
Content-Type: application/json

{
    "name": "Perry",
    "animalType": "Blötdjur",
    "otherInfo": "grön, med hatt"
    
}

###

DELETE http://localhost:3000/api/animals/b6a89990-1efb-11ec-82cd-43c8fc564042


###

PUT http://localhost:3000/api/animals/ec772430-1ad5-11ec-b719-394145ceba08
Content-Type: application/json

{
    
    "name": "Perry",
    "animalType": "Blötdjur",
    "otherInfo": "grön, med hatt"
}


